services:

  nginx:
    build: ./compose/prod/nginx
    image: cell_store_nginx
    volumes:
      - staticfiles:/cell_store/staticfiles
      - mediafiles:/cell_store/mediafiles
    ports:
      - 443:443
    depends_on:
      - web


  web:
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    command: ./compose/prod/django/start.sh
    image: cell_store_web
    ports:
      - 8000:8000
    volumes:
      - .:/cell_store/
      - staticfiles:/cell_store/staticfiles
      - mediafiles:/cell_store/mediafiles
    env_file:
      - ./environment/prod.sh
    restart:
      always

volumes:
  staticfiles:
  mediafiles:
